apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-api
  tags:
    - internal
spec:
  type: service
  lifecycle: production
  owner: felles_kartdatabase_-_team_lead
  providesApis:
    - security-champion-api-api
  system: fysak

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: security-champion-api-api
  tags:
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: felles_kartdatabase_-_team_lead
  definition: |
    openapi: "3.0.0"
    info:
        title: security-champion-api-api
  system: vegnett

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ny-entity
spec:
  type: library
  owner: felles_kartdatabase_-_team_lead
  lifecycle: production
  system: vegnett
