apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-api
  tags:
    - internal
spec:
  type: service-type
  lifecycle: production
  owner: skvis
  providesApis:
    - new-api
  system: utviklerportal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: new-api
spec:
  type: openapi
  owner: digibok
  lifecycle: production
