apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-service
  tags:
    - internal
spec:
  type: service
  lifecycle: production
  owner: skvis
  providesApis:
    - api:default/security-champion-api-api
    - api:default/new-api
  system: utviklerportal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: security-champion-api-api
  tags:
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: skvis
  definition:
    $text: /api-schema.json

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: new-api
spec:
  type: openapi
  owner: group:default/skoop_-_tech_lead
  lifecycle: production
  definition:
    $text: /api-schema.json
