apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-api
  tags:
    - internal
spec:
  type: website
  lifecycle: development
  owner: skvis
  providesApis:
    - security-champion-api-api
  system: utviklerportal
