apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-service
  tags:
    - internal
spec:
  type: service
  lifecycle: production
  owner: skvis
  providesApis:
    - security-champion-api-api
  system: utviklerportal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: security-champion-api-api
  tags:
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: skvis
  definition:
    $text: /api-schema.json

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: this
spec:
  type: database
  owner: dataplattform

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: is
spec:
  type: s3-bucket
  owner: smia_-_product_owner

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new
spec:
  type: website
  owner: dataplattform
  lifecycle: production
  system: sikkerhetsmetrikker
  providesApis:
    - api:default/frisk-backend-api
  consumesApis:
    - api:default/frisk-backend-api
  dependsOn:
    - component:default/Norgeskart
