apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: security-champion-service
  tags:
    - internal
spec:
  type: service
  lifecycle: production
  owner: skvis
  providesApis:
    - security-champion-api-api
  system: utviklerportal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: security-champion-api-api
  tags:
    - internal
spec:
  type: openapi
  lifecycle: production
  owner: skvis
  definition:
    $text: /api-schema.json

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: new
spec:
  type: product-area
  owner: regelrett_1
  subdomainOf:
    - domain:default/primaerdata
    - domain:default/test

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: test
spec:
  type: product-area
  owner: regelrett_1
  subdomainOf:
    - domain:default/innsikt
