spring:
  application:
    name: security-champion-api



  datasource:
    url: jdbc:postgresql://localhost/secchamp?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=spire-kartverket-dev:europe-west1:security-champion-api-db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}



